variables:
    SolutionBaseName: 'NCS.DSS.Collections'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.1
    endpoint: 'GitHub (CDH)'

jobs:
# Test the branch name, the output of this job will satisfy the condition of one or neither of the subsequent jobs
- job: TestBranchName
  displayName: TestBranchName
  pool: Continuous Integration 02 - SSD - 160ACU

  variables:
    TestBranchNameScriptUrl: https://raw.githubusercontent.com/SkillsFundingAgency/dss-devops/master/Scripts/Test-BranchName.ps1
    TestBranchNameScriptFilePath: $(System.DefaultWorkingDirectory)\Test-BranchName.ps1

  steps:
  - task: PowerShell@2
    name: DownloadTestBranchNameScript
    displayName: 'Download Test-BranchName script'
    inputs:
     targetType: 'inline'
     script: Invoke-WebRequest -Uri $(TestBranchNameScriptUrl) -OutFile $(TestBranchNameScriptFilePath)
  - task: PowerShell@2
    name: ExecuteTestBranchNameScript
    displayName: Test-BranchName
    inputs:
     targetType: 'filePath'
     filePath: $(TestBranchNameScriptFilePath)
     arguments: '-BranchName $(Build.SourceBranchName) -PullRequestBranchName $(if ("$(Build.SourceBranchName)" -eq "merge") { "$(System.PullRequest.SourceBranch)" } else { "NotAPullRequest" } ) -PipelineType Build -Verbose'

# Build the app with the dfc-dotnetcore-build template.  Runs if the output of TestBranchName is Version2+
- job: BuildDotNetStandard
  displayName: Build-DotNetStandard
  dependsOn: TestBranchName
  condition: and(succeeded(), eq(dependencies.TestBranchName.outputs['ExecuteTestBranchNameScript.FunctionAppVersion'], 'Version2+'))
  pool:
    name: Continuous Integration 02 - SSD - 160ACU
    demands:
    - msbuild
    - visualstudio

  steps:
  - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-dotnetcore-build-notests.yml@dfc-devops
    parameters:
      SolutionBaseName: $(SolutionBaseName)
      BuildPlatform: $(BuildPlatform)
      BuildConfiguration: $(BuildConfiguration)
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/DeploymentPackages'
    inputs:
      sourceFolder: '$(build.artifactstagingdirectory)/Artifact/$(SolutionBaseName)'
      contents: '**'
      targetFolder: '$(build.artifactstagingdirectory)/DeploymentPackages'
  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/Azure'
    inputs:
      sourceFolder: 'Resources'
      contents: '**'
      targetFolder: '$(build.artifactstagingdirectory)/Azure'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Artifact: $(SolutionBaseName)'
    inputs:
      pathtoPublish: $(build.artifactstagingdirectory)
      artifactName: $(SolutionBaseName)
      publishLocation: container





