// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NCS.DSS.Collections.SysIntTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("AzureSearch")]
    public partial class AzureSearchFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AzureSearch.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AzureSearch", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "Title",
                        "GivenName",
                        "FamilyName",
                        "DateofBirth",
                        "DateOfRegistration",
                        "UniqueLearnerNumber",
                        "OptInUserResearch",
                        "OptInMarketResearch",
                        "DateOfTermination",
                        "ReasonForTermination",
                        "IntroducedBy",
                        "IntroducedByAdditionalInfo",
                        "LastModifiedDate"});
            table1.AddRow(new string[] {
                        "ERIN",
                        "4",
                        "Erin",
                        "Surname[FEATURE_TS]",
                        "Today -20Y",
                        "Now -3D",
                        "9999900001",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "AARON",
                        "4",
                        "Aaron",
                        "Surname[FEATURE_TS]",
                        "Today -21Y",
                        "Now -3D",
                        "9999900002",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "VERONICA",
                        "4",
                        "Veronica",
                        "Surname[FEATURE_TS]",
                        "Today -22Y",
                        "Now -3D",
                        "9999900003",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "CAMERON",
                        "4",
                        "Cameron",
                        "Surname[FEATURE_TS]",
                        "Today -23Y",
                        "Now -3D",
                        "9999900004",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "RONALD",
                        "4",
                        "Ronald",
                        "Surname[FEATURE_TS]",
                        "Today -24Y",
                        "Now -3D",
                        "9999900005",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "RON",
                        "4",
                        "Ron",
                        "Surname[FEATURE_TS]",
                        "Today -25Y",
                        "Now -3D",
                        "9999900006",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "RONNIE",
                        "4",
                        "Ronnie",
                        "Surname[FEATURE_TS]",
                        "Today -26Y",
                        "Now -3D",
                        "9999900007",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
#line 4
 testRunner.Given("I load test customer data for this feature:", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "Address1",
                        "Address2",
                        "Address3",
                        "Address4",
                        "Address5",
                        "PostCode",
                        "AlternativePostCode",
                        "Longitude",
                        "Latitude",
                        "EffectiveFrom",
                        "EffectiveTo",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
            table2.AddRow(new string[] {
                        "ERIN",
                        "1 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "B44 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table2.AddRow(new string[] {
                        "AARON",
                        "2 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "B44 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table2.AddRow(new string[] {
                        "VERONICA",
                        "3 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "B44 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table2.AddRow(new string[] {
                        "CAMERON",
                        "4 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "B44 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table2.AddRow(new string[] {
                        "RONALD",
                        "5 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "B44 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table2.AddRow(new string[] {
                        "RON",
                        "6 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "B44 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table2.AddRow(new string[] {
                        "RONNIE",
                        "7 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "B44 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
#line 15
 testRunner.Given("I load test address data for this feature:", ((string)(null)), table2, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "PreferredContactMethod",
                        "MobileNumber",
                        "HomeNumber",
                        "AlternativeNumber",
                        "EmailAddress",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
            table3.AddRow(new string[] {
                        "ERIN",
                        "4",
                        "07484503700",
                        "05100924950",
                        "08483057675",
                        "email1@domain2.test",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table3.AddRow(new string[] {
                        "AARON",
                        "4",
                        "07484503700",
                        "05100924950",
                        "08483057675",
                        "email2@domain2.test",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table3.AddRow(new string[] {
                        "VERONICA",
                        "4",
                        "07484503700",
                        "05100924950",
                        "08483057675",
                        "email3@domain2.test",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table3.AddRow(new string[] {
                        "CAMERON",
                        "4",
                        "07484503700",
                        "05100924950",
                        "08483057675",
                        "email4@domain2.test",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table3.AddRow(new string[] {
                        "RONALD",
                        "4",
                        "07484503700",
                        "05100924950",
                        "08483057675",
                        "email5@domain2.test",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table3.AddRow(new string[] {
                        "RON",
                        "4",
                        "07484503700",
                        "05100924950",
                        "08483057675",
                        "email6@domain2.test",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table3.AddRow(new string[] {
                        "RONNIE",
                        "4",
                        "07484503700",
                        "05100924950",
                        "08483057675",
                        "email7@domain2.test",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
#line 27
  testRunner.Given("I load test contact data for this feature:", ((string)(null)), table3, "Given ");
#line 39
 testRunner.Given("I have completed loading data and don\'t want to repeat for each test", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 40
 testRunner.And("I have confirmed all test data is now in the backup data store", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Synonym name search for Aaron")]
        public virtual void SynonymNameSearchForAaron()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Synonym name search for Aaron", null, ((string[])(null)));
#line 42
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "SearchTerm",
                        "Value"});
            table4.AddRow(new string[] {
                        "GivenName",
                        "erin"});
#line 43
 testRunner.Given("I enter a search with the following terms", ((string)(null)), table4, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "FilterTerm",
                        "Value"});
            table5.AddRow(new string[] {
                        "DateofBirth",
                        "gt 1953-02-13T00:00:00Z"});
#line 46
 testRunner.And("I filter the results as follows", ((string)(null)), table5, "And ");
#line 49
 testRunner.When("I submit the search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 50
 testRunner.Then("there should be a 200 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value1",
                        "Value2"});
            table6.AddRow(new string[] {
                        "Aaron",
                        "Erin"});
#line 51
 testRunner.And("the response should include \"GivenName\" matches for:", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "FieldName",
                        "Value"});
            table7.AddRow(new string[] {
                        "DateofBirth",
                        "1953-02-13T00:00:00Z"});
#line 54
 testRunner.And("the response should include results for:", ((string)(null)), table7, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Synonym name search for Ronnie")]
        public virtual void SynonymNameSearchForRonnie()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Synonym name search for Ronnie", null, ((string[])(null)));
#line 58
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "SearchTerm",
                        "Value"});
            table8.AddRow(new string[] {
                        "GivenName",
                        "Ronnie"});
#line 59
 testRunner.Given("I enter a search with the following terms", ((string)(null)), table8, "Given ");
#line 62
 testRunner.When("I submit the search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 63
 testRunner.Then("there should be a 200 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Value1",
                        "Value2",
                        "Value3",
                        "Value4",
                        "Value5",
                        "Value6"});
            table9.AddRow(new string[] {
                        "Aaron",
                        "Ron",
                        "Veronica",
                        "Cameron",
                        "RONALD",
                        "Ronnie"});
#line 64
 testRunner.And("the response should include \"GivenName\" matches for:", ((string)(null)), table9, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search with OR")]
        public virtual void SearchWithOR()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search with OR", null, ((string[])(null)));
#line 78
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Search with AND")]
        public virtual void SearchWithAND()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Search with AND", null, ((string[])(null)));
#line 80
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Restrict search results")]
        public virtual void RestrictSearchResults()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Restrict search results", null, ((string[])(null)));
#line 82
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "SearchTerm",
                        "Value"});
            table10.AddRow(new string[] {
                        "FamilyName",
                        "SM*"});
#line 83
 testRunner.Given("I enter a search with the following terms", ((string)(null)), table10, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field1",
                        "Field2",
                        "Field3",
                        "Field4"});
            table11.AddRow(new string[] {
                        "CustomerId",
                        "GivenName",
                        "FamilyName",
                        "DateofBirth"});
#line 86
 testRunner.And("I restrict the returned fields to", ((string)(null)), table11, "And ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "FilterTerm",
                        "Value"});
            table12.AddRow(new string[] {
                        "DateofBirth",
                        "gt 1970-01-01"});
#line 89
 testRunner.And("I filter the results as follows", ((string)(null)), table12, "And ");
#line 92
 testRunner.When("I submit the search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 93
 testRunner.Then("there should be a 200 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field1",
                        "Field2",
                        "Field3",
                        "Field4"});
            table13.AddRow(new string[] {
                        "CustomerId",
                        "GivenName",
                        "FamilyName",
                        "DateofBirth"});
#line 94
 testRunner.And("The response includes values for", ((string)(null)), table13, "And ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "Field1",
                        "Field2",
                        "Field3",
                        "Field4",
                        "Field5",
                        "Field6",
                        "Field7",
                        "Field8",
                        "Field9",
                        "Field10",
                        "Field11"});
            table14.AddRow(new string[] {
                        "DateOfRegistration",
                        "Title",
                        "UniqueLearnerNumber",
                        "Gender",
                        "OptInUserResearch",
                        "OptInMarketResearch",
                        "DateOfTermination",
                        "IntroducedBy",
                        "IntroducedByAdditionalInfo",
                        "LastModifiedDate",
                        "LastModifiedTouchpointID"});
#line 97
 testRunner.And("The response includes no values for", ((string)(null)), table14, "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View 1st page of paginated results")]
        public virtual void View1StPageOfPaginatedResults()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View 1st page of paginated results", null, ((string[])(null)));
#line 102
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "SearchTerm",
                        "Value"});
            table15.AddRow(new string[] {
                        "FamilyName",
                        "SM*"});
#line 103
 testRunner.Given("I enter a search with the following terms", ((string)(null)), table15, "Given ");
#line 106
    testRunner.And("I request a count of records", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 107
 testRunner.And("I request a page limit of 10 records", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 108
 testRunner.When("I request page 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 109
 testRunner.Then("there should be a 200 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 110
 testRunner.And("the number of records returned should be 10", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View 2nd page of paginated results")]
        public virtual void View2NdPageOfPaginatedResults()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View 2nd page of paginated results", null, ((string[])(null)));
#line 112
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "SearchTerm",
                        "Value"});
            table16.AddRow(new string[] {
                        "FamilyName",
                        "SM*"});
#line 113
 testRunner.Given("I enter a search with the following terms", ((string)(null)), table16, "Given ");
#line 116
    testRunner.And("I request a count of records", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 117
 testRunner.And("I request a page limit of 10 records", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 118
 testRunner.And("I request page 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 119
 testRunner.And("I remember the records returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 120
 testRunner.When("I request page 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 121
 testRunner.Then("there should be a 200 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 122
 testRunner.And("the number of records returned should be 10", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
 testRunner.And("the records should not include the ealier results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("View last page of paginated results")]
        public virtual void ViewLastPageOfPaginatedResults()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("View last page of paginated results", null, ((string[])(null)));
#line 125
 this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "SearchTerm",
                        "Value"});
            table17.AddRow(new string[] {
                        "FamilyName",
                        "SM*"});
#line 126
 testRunner.Given("I enter a search with the following terms", ((string)(null)), table17, "Given ");
#line 129
    testRunner.And("I request a count of records", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 130
 testRunner.And("I request a page limit of 10 records", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
 testRunner.And("I request page 1", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
 testRunner.And("I remember the records returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 133
 testRunner.And("I request page 2", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 134
 testRunner.And("I remember the records returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 135
 testRunner.When("I request the last page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 136
 testRunner.Then("there should be a 200 response", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 137
 testRunner.Then("the remainder of the results are returned", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 138
 testRunner.And("the records should not include the ealier results", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
