// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NCS.DSS.Collections.SysIntTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ReportData_reportingperiod")]
    public partial class ReportData_ReportingperiodFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ReportData_ReportingPeriod"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "ReportData_reportingperiod", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "TouchPoint",
                        "Title",
                        "GivenName",
                        "FamilyName",
                        "DateofBirth",
                        "DateOfRegistration",
                        "UniqueLearnerNumber",
                        "OptInUserResearch",
                        "OptInMarketResearch",
                        "DateOfTermination",
                        "ReasonForTermination",
                        "IntroducedBy",
                        "IntroducedByAdditionalInfo",
                        "LastModifiedDate"});
            table1.AddRow(new string[] {
                        "COL1001_KEYDATES1",
                        "",
                        "4",
                        "Barry",
                        "tsone",
                        "Today -21Y",
                        "Now -3D",
                        "9999900030",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1002_KEYDATES2",
                        "",
                        "4",
                        "Terry",
                        "tstwo",
                        "Today -21Y",
                        "Now -3D",
                        "9999900031",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1003_KEYDATES3",
                        "",
                        "4",
                        "Quest",
                        "tsthree",
                        "Today -21Y",
                        "Now -3D",
                        "9999900032",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1004_KEYDATES4",
                        "",
                        "4",
                        "Sam",
                        "tsfour",
                        "Today -21Y",
                        "Now -3D",
                        "9999900033",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1005_KEYDATES5",
                        "",
                        "4",
                        "Gerry",
                        "tsfive",
                        "Today -21Y",
                        "Now -3D",
                        "9999900034",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1007_KEYDATES7",
                        "",
                        "4",
                        "Chop",
                        "tsseven",
                        "Today -21Y",
                        "Now -3D",
                        "9999900036",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1009_KEYDATES9",
                        "",
                        "4",
                        "Garry",
                        "tsnine",
                        "Today -21Y",
                        "Now -3D",
                        "9999900038",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1010_KEYDATES10",
                        "",
                        "4",
                        "Shim",
                        "tsten",
                        "Today -21Y",
                        "Now -3D",
                        "9999900039",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1011_KEYDATES11",
                        "",
                        "4",
                        "Connie",
                        "tseleven",
                        "Today -21Y",
                        "Now -3D",
                        "9999900040",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1012_KEYDATES12",
                        "",
                        "4",
                        "Bas",
                        "tstwelve",
                        "Today -21Y",
                        "Now -3D",
                        "9999900041",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1013_KEYDATES13",
                        "",
                        "4",
                        "Tim",
                        "tsthirteen",
                        "Today -21Y",
                        "Now -3D",
                        "9999900042",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1014_KEYDATES14",
                        "",
                        "4",
                        "Gray",
                        "tsfourteen",
                        "Today -21Y",
                        "Now -3D",
                        "9999900043",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
#line 5
testRunner.Given("I load test customer data for this feature:", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "Address1",
                        "Address2",
                        "Address3",
                        "Address4",
                        "Address5",
                        "PostCode",
                        "AlternativePostCode",
                        "Longitude",
                        "Latitude",
                        "EffectiveFrom",
                        "EffectiveTo",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
            table2.AddRow(new string[] {
                        "COL1001_KEYDATES1",
                        "1 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "P01 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table2.AddRow(new string[] {
                        "COL1003_KEYDATES3",
                        "2 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "P02 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "2018-01-23T00:00:00Z",
                        "2019-01-23T00:00:00Z",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table2.AddRow(new string[] {
                        "COL1005_KEYDATES5",
                        "3 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "P03 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table2.AddRow(new string[] {
                        "COL1010_KEYDATES10",
                        "4 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "B33 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "90000001"});
            table2.AddRow(new string[] {
                        "COL1010_KEYDATES10",
                        "4a Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "B33 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "",
                        "90000001"});
            table2.AddRow(new string[] {
                        "COL1011_KEYDATES11",
                        "10a Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "B39 9EX",
                        "EC2P 2AG",
                        "",
                        "",
                        "2019-01-24T00:00:00Z",
                        "",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table2.AddRow(new string[] {
                        "COL1012_KEYDATES12",
                        "11 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "B40 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table2.AddRow(new string[] {
                        "COL1013_KEYDATES13",
                        "12 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "B41 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table2.AddRow(new string[] {
                        "COL1014_KEYDATES14",
                        "13 Lake Street",
                        "North Walsham",
                        "",
                        "",
                        "",
                        "B41 9UX",
                        "EC2P 2AG",
                        "",
                        "",
                        "",
                        "",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
#line 21
testRunner.And("I load test address data for this feature:", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "PreferredContactMethod",
                        "MobileNumber",
                        "HomeNumber",
                        "AlternativeNumber",
                        "EmailAddress",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
#line 33
testRunner.And("I load test contact data for this feature:", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "TouchPoint",
                        "AdviserDetailsId",
                        "DateandTimeOfInteraction",
                        "Channel",
                        "InteractionType",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
            table4.AddRow(new string[] {
                        "COL1001_KEYDATES1",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1002_KEYDATES2",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-03-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1003_KEYDATES3",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1004_KEYDATES4",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1005_KEYDATES5",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1007_KEYDATES7",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-03-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1009_KEYDATES9",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1010_KEYDATES10",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1011_KEYDATES11",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1012_KEYDATES12",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1013_KEYDATES13",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-03-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1014_KEYDATES14",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
#line 36
 testRunner.And("I load test interaction data for this feature", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "ParentRef",
                        "DateandTimeOfSession",
                        "VenuePostCode",
                        "SessionAttended",
                        "ReasonForNonAttendance",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
            table5.AddRow(new string[] {
                        "COL1001_KEYDATES1",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "2019-04-05T00:00:00Z",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1002_KEYDATES2",
                        "1",
                        "2019-03-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "2019-03-01T00:00:00Z",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1003_KEYDATES3",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "2019-04-05T00:00:00Z",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1004_KEYDATES4",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "2019-04-05T00:00:00Z",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1005_KEYDATES5",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "2019-04-05T00:00:00Z",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1007_KEYDATES7",
                        "1",
                        "2019-03-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "2019-03-01T00:00:00Z",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1009_KEYDATES9",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "2019-04-05T00:00:00Z",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1010_KEYDATES10",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "2019-04-05T00:00:00Z",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1011_KEYDATES11",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "2019-04-05T00:00:00Z",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1012_KEYDATES12",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "2019-04-05T00:00:00Z",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1013_KEYDATES13",
                        "1",
                        "2019-03-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "2019-03-01T00:00:00Z",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1014_KEYDATES14",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "2019-04-05T00:00:00Z",
                        "90000001"});
#line 52
 testRunner.And("I load test session data for the feature", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "ParentRef",
                        "DateActionPlanCreated",
                        "CustomerCharterShownToCustomer",
                        "DateAndTimeCharterShown",
                        "DateActionPlanSentToCustomer",
                        "ActionPlanDeliveryMethod",
                        "DateActionPlanAcknowledged",
                        "PriorityCustomer",
                        "CurrentSituation"});
            table6.AddRow(new string[] {
                        "COL1001_KEYDATES1",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "true",
                        "2019-04-05T00:00:00Z",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1002_KEYDATES2",
                        "1",
                        "2019-03-01T00:00:00Z",
                        "true",
                        "2019-03-01T00:00:00Z",
                        "2019-03-01T00:00:00Z",
                        "1",
                        "2019-03-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1003_KEYDATES3",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "true",
                        "2019-04-05T00:00:00Z",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1004_KEYDATES4",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "true",
                        "2019-04-05T00:00:00Z",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1005_KEYDATES5",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "true",
                        "2019-04-05T00:00:00Z",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1007_KEYDATES7",
                        "1",
                        "2019-03-01T00:00:00Z",
                        "true",
                        "2019-03-01T00:00:00Z",
                        "2019-03-01T00:00:00Z",
                        "1",
                        "2019-03-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1009_KEYDATES9",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "true",
                        "2019-04-05T00:00:00Z",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1010_KEYDATES10",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "true",
                        "2019-04-05T00:00:00Z",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1011_KEYDATES11",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "true",
                        "2019-04-05T00:00:00Z",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1012_KEYDATES12",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "true",
                        "2019-04-05T00:00:00Z",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1013_KEYDATES13",
                        "1",
                        "2019-03-01T00:00:00Z",
                        "true",
                        "2019-03-01T00:00:00Z",
                        "2019-03-01T00:00:00Z",
                        "1",
                        "2019-03-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1014_KEYDATES14",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "true",
                        "2019-04-05T00:00:00Z",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "2019-04-05T00:00:00Z",
                        "1",
                        "looking for work26"});
#line 67
testRunner.And("I load action plan data for the feature", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "ParentRef",
                        "OutcomeType",
                        "TouchPoint",
                        "ClaimedPriorityGroup",
                        "OutcomeClaimedDate",
                        "OutcomeEffectiveDate"});
            table7.AddRow(new string[] {
                        "COL1001_KEYDATES1",
                        "1",
                        "1",
                        "",
                        "99",
                        "2019-04-03T00:00:00Z",
                        "2019-04-03T00:00:00Z"});
            table7.AddRow(new string[] {
                        "COL1002_KEYDATES2",
                        "1",
                        "2",
                        "",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "2019-03-31T23:59:59Z"});
            table7.AddRow(new string[] {
                        "COL1003_KEYDATES3",
                        "1",
                        "3",
                        "",
                        "2",
                        "2019-04-03T00:00:00Z",
                        "2019-04-01T00:00:00Z"});
            table7.AddRow(new string[] {
                        "COL1004_KEYDATES4",
                        "1",
                        "3",
                        "",
                        "5",
                        "2020-03-30T00:00:00Z",
                        "2020-04-01T00:00:00Z"});
            table7.AddRow(new string[] {
                        "COL1005_KEYDATES5",
                        "1",
                        "1",
                        "",
                        "99",
                        "2019-05-09T00:00:00Z",
                        "2019-05-09T00:00:00Z"});
            table7.AddRow(new string[] {
                        "COL1009_KEYDATES9",
                        "1",
                        "3",
                        "",
                        "6",
                        "2020-04-01T00:00:00Z",
                        "2020-03-30T00:00:00Z"});
            table7.AddRow(new string[] {
                        "COL1010_KEYDATES10",
                        "1",
                        "1",
                        "",
                        "4",
                        "2020-03-31T23:59:59Z",
                        "2020-03-30T23:59:59Z"});
            table7.AddRow(new string[] {
                        "COL1011_KEYDATES11",
                        "1",
                        "1",
                        "",
                        "99",
                        "",
                        "2019-08-09T00:00:00Z"});
            table7.AddRow(new string[] {
                        "COL1012_KEYDATES12",
                        "1",
                        "2",
                        "",
                        "6",
                        "",
                        ""});
            table7.AddRow(new string[] {
                        "COL1013_KEYDATES13",
                        "1",
                        "3",
                        "",
                        "4",
                        "2019-03-31T23:59:59Z",
                        "2019-03-31T23:59:59Z"});
            table7.AddRow(new string[] {
                        "COL1014_KEYDATES14",
                        "1",
                        "3",
                        "",
                        "99",
                        "2020-04-01T00:00:00Z",
                        "2020-04-01T00:00:00Z"});
#line 82
testRunner.And("I load outcome data for the feature", ((string)(null)), table7, "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "SessionRef",
                        "DateandTimeOfSession"});
#line 96
testRunner.And("I update the following sessions", ((string)(null)), table8, "And ");
#line 101
testRunner.And("I have made any data fudging updates required", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 102
testRunner.And("I have confirmed all test data is now in the backup data store", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 103
testRunner.And("the report period start date is \"2019-04-01\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 104
testRunner.And("the report period end date is \"2020-03-31\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 105
testRunner.And("a request has been made and the report data is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 106
testRunner.And("I have completed loading data and don\'t want to repeat for each test", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Outcome claimed and effective date checks")]
        public virtual void OutcomeClaimedAndEffectiveDateChecks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Outcome claimed and effective date checks", null, ((string[])(null)));
#line 109
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 110
  testRunner.When("I check the report data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table9.AddRow(new string[] {
                        "Today -21Y",
                        "P01 9UX",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "1",
                        "2019-04-03",
                        "0"});
#line 111
  testRunner.Then("Outcome 1 for test customer \"COL1001_KEYDATES1\" is included in the report with th" +
                    "e following values", ((string)(null)), table9, "Then ");
#line 114
  testRunner.Then("Outcome 1 for test customer \"COL1002_KEYDATES2\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table10.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "3",
                        "2019-04-01",
                        "1"});
#line 115
  testRunner.Then("Outcome 1 for test customer \"COL1003_KEYDATES3\" is included in the report with th" +
                    "e following values", ((string)(null)), table10, "Then ");
#line 118
  testRunner.Then("Outcome 1 for test customer \"COL1004_KEYDATES4\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table11.AddRow(new string[] {
                        "Today -21Y",
                        "P03 9UX",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "1",
                        "2019-05-09",
                        "0"});
#line 119
  testRunner.Then("Outcome 1 for test customer \"COL1005_KEYDATES5\" is included in the report with th" +
                    "e following values", ((string)(null)), table11, "Then ");
#line 122
  testRunner.Then("Outcome 1 for test customer \"COL1009_KEYDATES9\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table12.AddRow(new string[] {
                        "Today -21Y",
                        "B33 9UX",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "1",
                        "2020-03-30",
                        "1"});
#line 123
  testRunner.Then("Outcome 1 for test customer \"COL1010_KEYDATES10\" is included in the report with t" +
                    "he following values", ((string)(null)), table12, "Then ");
#line 126
  testRunner.Then("Outcome 1 for test customer \"COL1011_KEYDATES11\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 127
  testRunner.Then("Outcome 1 for test customer \"COL1012_KEYDATES12\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 128
  testRunner.Then("Outcome 1 for test customer \"COL1013_KEYDATES13\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 129
  testRunner.Then("Outcome 1 for test customer \"COL1014_KEYDATES14\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

