// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NCS.DSS.Collections.SysIntTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ReportData_MultipleOutcomes")]
    public partial class ReportData_MultipleOutcomesFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ReportData_MultipleOutcomes.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "ReportData_MultipleOutcomes", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 3
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "TouchPoint",
                        "Title",
                        "GivenName",
                        "FamilyName",
                        "DateofBirth",
                        "DateOfRegistration",
                        "UniqueLearnerNumber",
                        "OptInUserResearch",
                        "OptInMarketResearch",
                        "DateOfTermination",
                        "ReasonForTermination",
                        "IntroducedBy",
                        "IntroducedByAdditionalInfo",
                        "LastModifiedDate"});
            table1.AddRow(new string[] {
                        "COL1030_OUTCOMES1",
                        "",
                        "4",
                        "Dan",
                        "tsthirty",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1031_OUTCOMES2",
                        "",
                        "4",
                        "Dan",
                        "tsthirtyone",
                        "Today -21Y",
                        "Now -3D",
                        "9999900050",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1032_OUTCOMES3",
                        "",
                        "4",
                        "Dan",
                        "tsthirtytwo",
                        "Today -21Y",
                        "Now -3D",
                        "9999900051",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1033_OUTCOMES4",
                        "",
                        "4",
                        "Dan",
                        "tsthirtythree",
                        "Today -21Y",
                        "Now -3D",
                        "9999900051",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1034_OUTCOMES5",
                        "",
                        "4",
                        "Dan",
                        "tsthirtyfour",
                        "Today -21Y",
                        "Now -3D",
                        "9999900051",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1035_OUTCOMES6",
                        "",
                        "4",
                        "Dan",
                        "tsthiryfive",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1036_OUTCOMES7",
                        "",
                        "4",
                        "Dan",
                        "tsthirtysix",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1037_OUTCOMES8",
                        "",
                        "4",
                        "Dan",
                        "tsthirtyseven",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1038_OUTCOMES9",
                        "",
                        "4",
                        "Dan",
                        "tsthirtyeight",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1039_OUTCOMES10",
                        "",
                        "4",
                        "Dan",
                        "tsthirtynine",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1040_OUTCOMES11",
                        "",
                        "4",
                        "Dan",
                        "tsforty",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1042a_OUTCOMES14",
                        "",
                        "4",
                        "Dan",
                        "tsfortya",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
#line 5
testRunner.Given("I load test customer data for this feature:", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "Address1",
                        "Address2",
                        "Address3",
                        "Address4",
                        "Address5",
                        "PostCode",
                        "AlternativePostCode",
                        "Longitude",
                        "Latitude",
                        "EffectiveFrom",
                        "EffectiveTo",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
#line 21
testRunner.And("I load test address data for this feature:", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "PreferredContactMethod",
                        "MobileNumber",
                        "HomeNumber",
                        "AlternativeNumber",
                        "EmailAddress",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
#line 24
testRunner.And("I load test contact data for this feature:", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "TouchPoint",
                        "AdviserDetailsId",
                        "DateandTimeOfInteraction",
                        "Channel",
                        "InteractionType",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
            table4.AddRow(new string[] {
                        "COL1030_OUTCOMES1",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1031_OUTCOMES2",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1032_OUTCOMES3",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1033_OUTCOMES4",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1034_OUTCOMES5",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1035_OUTCOMES6",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1036_OUTCOMES7",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1037_OUTCOMES8",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1038_OUTCOMES9",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1039_OUTCOMES10",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1040_OUTCOMES11",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1042a_OUTCOMES14",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1030_OUTCOMES1",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-03-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1031_OUTCOMES2",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-03-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1032_OUTCOMES3",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-03-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1033_OUTCOMES4",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-03-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1034_OUTCOMES5",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-03-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1035_OUTCOMES6",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-03-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1036_OUTCOMES7",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-03-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1037_OUTCOMES8",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-03-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1038_OUTCOMES9",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-02-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1039_OUTCOMES10",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-03-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1040_OUTCOMES11",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2019-03-01T00:00:00Z",
                        "2",
                        "3",
                        "2019-01-23T00:00:00Z",
                        "90000001"});
#line 27
 testRunner.And("I load test interaction data for this feature", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "ParentRef",
                        "DateandTimeOfSession",
                        "VenuePostCode",
                        "SessionAttended",
                        "ReasonForNonAttendance",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
            table5.AddRow(new string[] {
                        "COL1030_OUTCOMES1",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1031_OUTCOMES2",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1032_OUTCOMES3",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1033_OUTCOMES4",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1034_OUTCOMES5",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1035_OUTCOMES6",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1036_OUTCOMES7",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "false",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1037_OUTCOMES8",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1038_OUTCOMES9",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1039_OUTCOMES10",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1040_OUTCOMES11",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1042a_OUTCOMES14",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
#line 54
 testRunner.And("I load test session data for the feature", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "ParentRef",
                        "DateActionPlanCreated",
                        "CustomerCharterShownToCustomer",
                        "DateAndTimeCharterShown",
                        "DateActionPlanSentToCustomer",
                        "ActionPlanDeliveryMethod",
                        "DateActionPlanAcknowledged",
                        "PriorityCustomer",
                        "CurrentSituation"});
            table6.AddRow(new string[] {
                        "COL1030_OUTCOMES1",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "true",
                        "2019-04-01T00:00:00Z",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1031_OUTCOMES2",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "true",
                        "2019-04-01T00:00:00Z",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1032_OUTCOMES3",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "true",
                        "2019-04-01T00:00:00Z",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1033_OUTCOMES4",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "true",
                        "2019-04-01T00:00:00Z",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1034_OUTCOMES5",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "true",
                        "2019-04-01T00:00:00Z",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1035_OUTCOMES6",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "true",
                        "2019-04-01T00:00:00Z",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1036_OUTCOMES7",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "true",
                        "2019-04-01T00:00:00Z",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1037_OUTCOMES8",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "true",
                        "2019-04-01T00:00:00Z",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1038_OUTCOMES9",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "true",
                        "2019-04-01T00:00:00Z",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1039_OUTCOMES10",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "true",
                        "2019-04-01T00:00:00Z",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1040_OUTCOMES11",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "true",
                        "2019-04-01T00:00:00Z",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1042a_OUTCOMES14",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "true",
                        "2019-04-01T00:00:00Z",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "2019-04-01T00:00:00Z",
                        "1",
                        "looking for work26"});
#line 69
testRunner.And("I load action plan data for the feature", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "ParentRef",
                        "OutcomeType",
                        "TouchPoint",
                        "ClaimedPriorityGroup",
                        "OutcomeClaimedDate",
                        "OutcomeEffectiveDate",
                        "LastModifiedDate"});
            table7.AddRow(new string[] {
                        "COL1030_OUTCOMES1",
                        "1",
                        "1",
                        "",
                        "1",
                        "2019-12-03T00:00:00Z",
                        "2019-04-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1030_OUTCOMES1",
                        "1",
                        "2",
                        "",
                        "1",
                        "2019-12-03T00:00:00Z",
                        "2019-05-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1030_OUTCOMES1",
                        "1",
                        "3",
                        "",
                        "1",
                        "2019-12-03T00:00:00Z",
                        "2019-06-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1031_OUTCOMES2",
                        "1",
                        "1",
                        "",
                        "2",
                        "2019-12-03T00:00:00Z",
                        "2019-04-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1031_OUTCOMES2",
                        "1",
                        "2",
                        "",
                        "2",
                        "2019-12-03T00:00:00Z",
                        "2019-05-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1031_OUTCOMES2",
                        "1",
                        "4",
                        "",
                        "99",
                        "2019-12-03T00:00:00Z",
                        "2019-06-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1032_OUTCOMES3",
                        "1",
                        "1",
                        "",
                        "1",
                        "2019-12-03T00:00:00Z",
                        "2019-04-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1032_OUTCOMES3",
                        "1",
                        "2",
                        "",
                        "99",
                        "2019-12-03T00:00:00Z",
                        "2019-05-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1032_OUTCOMES3",
                        "1",
                        "5",
                        "",
                        "99",
                        "2019-12-03T00:00:00Z",
                        "2019-06-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1034_OUTCOMES5",
                        "1",
                        "2",
                        "",
                        "2",
                        "2019-12-03T00:00:00Z",
                        "2019-04-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1034_OUTCOMES5",
                        "1",
                        "1",
                        "",
                        "2",
                        "2019-12-03T00:00:00Z",
                        "2019-05-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1034_OUTCOMES5",
                        "1",
                        "2",
                        "",
                        "2",
                        "2019-12-03T00:00:00Z",
                        "2019-06-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1034_OUTCOMES5",
                        "1",
                        "3",
                        "",
                        "2",
                        "2019-12-03T00:00:00Z",
                        "2019-07-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1035_OUTCOMES6",
                        "1",
                        "1",
                        "",
                        "99",
                        "2019-12-03T00:00:00Z",
                        "2019-04-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1035_OUTCOMES6",
                        "1",
                        "2",
                        "",
                        "99",
                        "2019-12-03T00:00:00Z",
                        "2019-05-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1035_OUTCOMES6",
                        "1",
                        "3",
                        "",
                        "99",
                        "2019-12-03T00:00:00Z",
                        "2019-06-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1035_OUTCOMES6",
                        "1",
                        "5",
                        "",
                        "99",
                        "2019-08-03T00:00:00Z",
                        "2019-08-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1035_OUTCOMES6",
                        "1",
                        "5",
                        "",
                        "99",
                        "2019-08-03T00:00:00Z",
                        "2019-08-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1036_OUTCOMES7",
                        "1",
                        "1",
                        "",
                        "1",
                        "2019-12-03T00:00:00Z",
                        "2019-04-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1036_OUTCOMES7",
                        "1",
                        "2",
                        "",
                        "1",
                        "2019-12-03T00:00:00Z",
                        "2019-05-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1036_OUTCOMES7",
                        "1",
                        "4",
                        "",
                        "1",
                        "2019-12-03T00:00:00Z",
                        "2019-06-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1036_OUTCOMES7",
                        "1",
                        "3",
                        "",
                        "1",
                        "2019-12-03T00:00:00Z",
                        "2019-07-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1036_OUTCOMES7",
                        "1",
                        "5",
                        "",
                        "1",
                        "2019-08-03T00:00:00Z",
                        "2019-08-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1037_OUTCOMES8",
                        "1",
                        "5",
                        "",
                        "2",
                        "2019-12-03T00:00:00Z",
                        "2019-04-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1037_OUTCOMES8",
                        "1",
                        "3",
                        "",
                        "2",
                        "2019-12-03T00:00:00Z",
                        "2019-05-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1037_OUTCOMES8",
                        "1",
                        "4",
                        "",
                        "2",
                        "2019-12-03T00:00:00Z",
                        "2019-06-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1037_OUTCOMES8",
                        "1",
                        "2",
                        "",
                        "2",
                        "2019-12-03T00:00:00Z",
                        "2019-07-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1037_OUTCOMES8",
                        "1",
                        "1",
                        "",
                        "2",
                        "2019-08-03T00:00:00Z",
                        "2019-08-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1038_OUTCOMES9",
                        "1",
                        "1",
                        "0000000999",
                        "99",
                        "2019-12-03T00:00:00Z",
                        "2019-04-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1038_OUTCOMES9",
                        "1",
                        "1",
                        "",
                        "99",
                        "2019-12-03T00:00:00Z",
                        "2019-05-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1039_OUTCOMES10",
                        "1",
                        "1",
                        "9999999999",
                        "1",
                        "2019-12-03T00:00:00Z",
                        "2019-06-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1039_OUTCOMES10",
                        "1",
                        "1",
                        "",
                        "1",
                        "2019-12-03T00:00:00Z",
                        "2019-07-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1040_OUTCOMES11",
                        "1",
                        "1",
                        "",
                        "1",
                        "2019-12-03T00:00:00Z",
                        "2019-06-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1040_OUTCOMES11",
                        "1",
                        "1",
                        "9999999999",
                        "1",
                        "2019-12-03T00:00:00Z",
                        "2019-07-03T00:00:00Z",
                        ""});
            table7.AddRow(new string[] {
                        "COL1042a_OUTCOMES14",
                        "1",
                        "1",
                        "",
                        "99",
                        "2019-05-04T00:00:00Z",
                        "2019-05-04T00:00:00Z",
                        "2019-05-04T00:00:00Z"});
            table7.AddRow(new string[] {
                        "COL1042a_OUTCOMES14",
                        "1",
                        "1",
                        "",
                        "99",
                        "2019-05-04T00:00:00Z",
                        "2019-05-04T00:00:00Z",
                        "2019-05-04T00:00:00Z"});
#line 84
testRunner.And("I load outcome data for the feature", ((string)(null)), table7, "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "SessionRef",
                        "DateandTimeOfSession"});
#line 123
testRunner.And("I update the following sessions", ((string)(null)), table8, "And ");
#line 128
testRunner.And("I have made any data fudging updates required", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 129
testRunner.And("I have confirmed all test data is now in the backup data store", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 130
testRunner.And("the report period start date is \"2019-04-01\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
testRunner.And("the report period end date is \"2020-03-31\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 132
testRunner.And("a request has been made and the report data is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 133
testRunner.And("I have completed loading data and don\'t want to repeat for each test", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("All submitted outcomes are valid")]
        public virtual void AllSubmittedOutcomesAreValid()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("All submitted outcomes are valid", null, ((string[])(null)));
#line 135
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 136
  testRunner.When("I check the report data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table9.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "1",
                        "2019-04-03",
                        "1"});
#line 137
  testRunner.Then("Outcome 1 for test customer \"COL1030_OUTCOMES1\" is included in the report with th" +
                    "e following values", ((string)(null)), table9, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table10.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "2",
                        "2019-05-03",
                        "1"});
#line 140
  testRunner.Then("Outcome 2 for test customer \"COL1030_OUTCOMES1\" is included in the report with th" +
                    "e following values", ((string)(null)), table10, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table11.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "3",
                        "2019-06-03",
                        "1"});
#line 143
  testRunner.Then("Outcome 3 for test customer \"COL1030_OUTCOMES1\" is included in the report with th" +
                    "e following values", ((string)(null)), table11, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table12.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "1",
                        "2019-04-03",
                        "1"});
#line 146
  testRunner.Then("Outcome 1 for test customer \"COL1031_OUTCOMES2\" is included in the report with th" +
                    "e following values", ((string)(null)), table12, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table13.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "2",
                        "2019-05-03",
                        "1"});
#line 149
  testRunner.Then("Outcome 2 for test customer \"COL1031_OUTCOMES2\" is included in the report with th" +
                    "e following values", ((string)(null)), table13, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table14.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "4",
                        "2019-06-03",
                        "0"});
#line 152
  testRunner.Then("Outcome 3 for test customer \"COL1031_OUTCOMES2\" is included in the report with th" +
                    "e following values", ((string)(null)), table14, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table15.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "1",
                        "2019-04-03",
                        "1"});
#line 155
  testRunner.Then("Outcome 1 for test customer \"COL1032_OUTCOMES3\" is included in the report with th" +
                    "e following values", ((string)(null)), table15, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table16.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "2",
                        "2019-05-03",
                        "0"});
#line 158
  testRunner.Then("Outcome 2 for test customer \"COL1032_OUTCOMES3\" is included in the report with th" +
                    "e following values", ((string)(null)), table16, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table17.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "5",
                        "2019-06-03",
                        "0"});
#line 161
  testRunner.Then("Outcome 3 for test customer \"COL1032_OUTCOMES3\" is included in the report with th" +
                    "e following values", ((string)(null)), table17, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Invalid Outcome are submitted where another of the same type is already present")]
        public virtual void InvalidOutcomeAreSubmittedWhereAnotherOfTheSameTypeIsAlreadyPresent()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Invalid Outcome are submitted where another of the same type is already present", null, ((string[])(null)));
#line 166
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 167
  testRunner.When("I check the report data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
            TechTalk.SpecFlow.Table table18 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table18.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "2",
                        "2019-04-03",
                        "1"});
#line 169
  testRunner.Then("Outcome 1 for test customer \"COL1034_OUTCOMES5\" is included in the report with th" +
                    "e following values", ((string)(null)), table18, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table19 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table19.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "1",
                        "2019-05-03",
                        "1"});
#line 172
  testRunner.Then("Outcome 2 for test customer \"COL1034_OUTCOMES5\" is included in the report with th" +
                    "e following values", ((string)(null)), table19, "Then ");
#line 175
  testRunner.Then("Outcome 3 for test customer \"COL1034_OUTCOMES5\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table20 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table20.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "3",
                        "2019-07-03",
                        "1"});
#line 176
  testRunner.Then("Outcome 4 for test customer \"COL1034_OUTCOMES5\" is included in the report with th" +
                    "e following values", ((string)(null)), table20, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table21 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table21.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "1",
                        "2019-04-03",
                        "0"});
#line 180
  testRunner.Then("Outcome 1 for test customer \"COL1035_OUTCOMES6\" is included in the report with th" +
                    "e following values", ((string)(null)), table21, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table22 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table22.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "2",
                        "2019-05-03",
                        "0"});
#line 183
  testRunner.Then("Outcome 2 for test customer \"COL1035_OUTCOMES6\" is included in the report with th" +
                    "e following values", ((string)(null)), table22, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table23 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table23.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "3",
                        "2019-06-03",
                        "0"});
#line 186
  testRunner.Then("Outcome 3 for test customer \"COL1035_OUTCOMES6\" is included in the report with th" +
                    "e following values", ((string)(null)), table23, "Then ");
#line 189
  testRunner.Then("Outcome 4 for test customer \"COL1035_OUTCOMES6\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 190
  testRunner.Then("Outcome 5 for test customer \"COL1035_OUTCOMES6\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table24 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table24.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "1",
                        "2019-04-03",
                        "1"});
#line 192
  testRunner.Then("Outcome 1 for test customer \"COL1036_OUTCOMES7\" is included in the report with th" +
                    "e following values", ((string)(null)), table24, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table25 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table25.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "2",
                        "2019-05-03",
                        "1"});
#line 195
  testRunner.Then("Outcome 2 for test customer \"COL1036_OUTCOMES7\" is included in the report with th" +
                    "e following values", ((string)(null)), table25, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table26 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table26.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "4",
                        "2019-06-03",
                        "1"});
#line 198
  testRunner.Then("Outcome 3 for test customer \"COL1036_OUTCOMES7\" is included in the report with th" +
                    "e following values", ((string)(null)), table26, "Then ");
#line 201
  testRunner.Then("Outcome 4 for test customer \"COL1036_OUTCOMES7\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 202
  testRunner.Then("Outcome 5 for test customer \"COL1036_OUTCOMES7\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table27 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table27.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "5",
                        "2019-04-03",
                        "1"});
#line 204
  testRunner.Then("Outcome 1 for test customer \"COL1037_OUTCOMES8\" is included in the report with th" +
                    "e following values", ((string)(null)), table27, "Then ");
#line 207
  testRunner.Then("Outcome 2 for test customer \"COL1037_OUTCOMES8\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 208
  testRunner.Then("Outcome 3 for test customer \"COL1037_OUTCOMES8\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table28 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table28.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "2",
                        "2019-07-03",
                        "1"});
#line 209
  testRunner.Then("Outcome 4 for test customer \"COL1037_OUTCOMES8\" is included in the report with th" +
                    "e following values", ((string)(null)), table28, "Then ");
#line hidden
            TechTalk.SpecFlow.Table table29 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table29.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "1",
                        "2019-08-03",
                        "1"});
#line 212
  testRunner.Then("Outcome 5 for test customer \"COL1037_OUTCOMES8\" is included in the report with th" +
                    "e following values", ((string)(null)), table29, "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Outcomes submitted by another party")]
        public virtual void OutcomesSubmittedByAnotherParty()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Outcomes submitted by another party", null, ((string[])(null)));
#line 217
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 218
  testRunner.When("I check the report data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 220
  testRunner.Then("Outcome 1 for test customer \"COL1038_OUTCOMES9\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table30 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table30.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "1",
                        "2019-05-03",
                        "0"});
#line 221
  testRunner.Then("Outcome 2 for test customer \"COL1038_OUTCOMES9\" is included in the report with th" +
                    "e following values", ((string)(null)), table30, "Then ");
#line 225
  testRunner.Then("Outcome 1 for test customer \"COL1039_OUTCOMES10\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 226
  testRunner.Then("Outcome 2 for test customer \"COL1039_OUTCOMES10\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            TechTalk.SpecFlow.Table table31 = new TechTalk.SpecFlow.Table(new string[] {
                        "DateOfBirth",
                        "HomePostCode",
                        "SessionDate",
                        "SubContractorId",
                        "AdviserName",
                        "OutcomeType",
                        "OutcomeEffectiveDate",
                        "OutcomePriorityCustomer"});
            table31.AddRow(new string[] {
                        "Today -21Y",
                        "",
                        "2019-04-01",
                        "",
                        "Billy Adviser",
                        "1",
                        "2019-06-03",
                        "1"});
#line 228
  testRunner.Then("Outcome 1 for test customer \"COL1040_OUTCOMES11\" is included in the report with t" +
                    "he following values", ((string)(null)), table31, "Then ");
#line 231
  testRunner.Then("Outcome 2 for test customer \"COL1040_OUTCOMES11\" is not included in the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Duplicate outcomes")]
        public virtual void DuplicateOutcomes()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Duplicate outcomes", null, ((string[])(null)));
#line 234
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 3
this.FeatureBackground();
#line 235
  testRunner.When("I check the report data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 237
  testRunner.Then("Either Outcome 1 or 2 for test customer \"COL1042a_OUTCOMES14\" is included in the " +
                    "report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

