// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.4.0.0
//      SpecFlow Generator Version:2.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace NCS.DSS.Collections.SysIntTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("ReportData_SessionClose")]
    public partial class ReportData_SessionCloseFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "ReportData_SessionClose.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-GB"), "ReportData_SessionClose", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 7
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "TouchPoint",
                        "Title",
                        "GivenName",
                        "FamilyName",
                        "DateofBirth",
                        "DateOfRegistration",
                        "UniqueLearnerNumber",
                        "OptInUserResearch",
                        "OptInMarketResearch",
                        "DateOfTermination",
                        "ReasonForTermination",
                        "IntroducedBy",
                        "IntroducedByAdditionalInfo",
                        "LastModifiedDate"});
            table1.AddRow(new string[] {
                        "COL1015_SESSIONWITHIN12MONTHS1",
                        "",
                        "4",
                        "Carter",
                        "tsfifteen",
                        "Today -21Y",
                        "Now -3D",
                        "9999900044",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1016_SESSIONWITHIN12MONTHS2",
                        "",
                        "4",
                        "Lil",
                        "tssixteen",
                        "Today -21Y",
                        "Now -3D",
                        "9999900045",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1017_SESSIONWITHIN13MONTHS3",
                        "",
                        "4",
                        "Marge",
                        "tsseventeen",
                        "Today -21Y",
                        "Now -3D",
                        "9999900046",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1018_SESSIONWITHIN12MONTHS4",
                        "",
                        "4",
                        "Sarah",
                        "tseighteen",
                        "Today -21Y",
                        "Now -3D",
                        "9999900047",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1019_SESSIONWITHIN12MONTHS5",
                        "",
                        "4",
                        "Dan",
                        "tsnineteen",
                        "Today -21Y",
                        "Now -3D",
                        "9999900048",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1020_SESSIONEXACTLY12MONTHS1",
                        "",
                        "4",
                        "Dan",
                        "tstwenty",
                        "Today -21Y",
                        "Now -3D",
                        "9999900049",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1021_SESSIONEXACTLY12MONTHS2",
                        "",
                        "4",
                        "Dan",
                        "tstwentyone",
                        "Today -21Y",
                        "Now -3D",
                        "9999900050",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1022_SESSIONEXACTLY13MONTHS3",
                        "",
                        "4",
                        "Dan",
                        "tstwentytwo",
                        "Today -21Y",
                        "Now -3D",
                        "9999900051",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1023_SESSIONEXACTLY12MONTHS4",
                        "",
                        "4",
                        "Dan",
                        "tstwentythree",
                        "Today -21Y",
                        "Now -3D",
                        "9999900052",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1024_SESSIONEXACTLY12MONTHS5",
                        "",
                        "4",
                        "Dan",
                        "tstwentyfour",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "1",
                        "ZZ_TESTDATA_ANON",
                        "2019-01-17T00:00:00Z"});
            table1.AddRow(new string[] {
                        "COL1025_SESSIONMORETHAN12MONTHS1",
                        "",
                        "4",
                        "Dan",
                        "tstwentyfive",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1026_SESSIONMORETHAN12MONTHS2",
                        "",
                        "4",
                        "Dan",
                        "tstwentysix",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1027_SESSIONMORETHAN13MONTHS3",
                        "",
                        "4",
                        "Dan",
                        "tstwentyseven",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1028_SESSIONMORETHAN12MONTHS4",
                        "",
                        "4",
                        "Dan",
                        "tstwentyeight",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
            table1.AddRow(new string[] {
                        "COL1029_SESSIONMORETHAN12MONTHS5",
                        "",
                        "4",
                        "Dan",
                        "tstwentynine",
                        "Today -21Y",
                        "Now -3D",
                        "9999900053",
                        "true",
                        "false",
                        "",
                        "",
                        "",
                        "",
                        ""});
#line 9
testRunner.Given("I load test customer data for this feature:", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "Address1",
                        "Address2",
                        "Address3",
                        "Address4",
                        "Address5",
                        "PostCode",
                        "AlternativePostCode",
                        "Longitude",
                        "Latitude",
                        "EffectiveFrom",
                        "EffectiveTo",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
#line 28
testRunner.And("I load test address data for this feature:", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "PreferredContactMethod",
                        "MobileNumber",
                        "HomeNumber",
                        "AlternativeNumber",
                        "EmailAddress",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
#line 31
testRunner.And("I load test contact data for this feature:", ((string)(null)), table3, "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "TouchPoint",
                        "AdviserDetailsId",
                        "DateandTimeOfInteraction",
                        "Channel",
                        "InteractionType",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
            table4.AddRow(new string[] {
                        "COL1015_SESSIONWITHIN12MONTHS1",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1016_SESSIONWITHIN12MONTHS2",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1017_SESSIONWITHIN13MONTHS3",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1018_SESSIONWITHIN12MONTHS4",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1019_SESSIONWITHIN12MONTHS5",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1020_SESSIONEXACTLY12MONTHS1",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1021_SESSIONEXACTLY12MONTHS2",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1022_SESSIONEXACTLY13MONTHS3",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1023_SESSIONEXACTLY12MONTHS4",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1024_SESSIONEXACTLY12MONTHS5",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1025_SESSIONMORETHAN12MONTHS1",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1026_SESSIONMORETHAN12MONTHS2",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1027_SESSIONMORETHAN13MONTHS3",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1028_SESSIONMORETHAN12MONTHS4",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
            table4.AddRow(new string[] {
                        "COL1029_SESSIONMORETHAN12MONTHS5",
                        "",
                        "bb940afb-1423-4999-a234-5a64a5c00831",
                        "2018-04-01T00:00:00Z",
                        "2",
                        "3",
                        "",
                        "90000001"});
#line 34
 testRunner.And("I load test interaction data for this feature", ((string)(null)), table4, "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "ParentRef",
                        "DateandTimeOfSession",
                        "VenuePostCode",
                        "SessionAttended",
                        "ReasonForNonAttendance",
                        "LastModifiedDate",
                        "LastModifiedTouchpointId"});
            table5.AddRow(new string[] {
                        "COL1015_SESSIONWITHIN12MONTHS1",
                        "1",
                        "2018-04-30T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1016_SESSIONWITHIN12MONTHS2",
                        "1",
                        "2018-04-30T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1017_SESSIONWITHIN13MONTHS3",
                        "1",
                        "2018-04-30T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1018_SESSIONWITHIN12MONTHS4",
                        "1",
                        "2018-04-30T23:59:59Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1019_SESSIONWITHIN12MONTHS5",
                        "1",
                        "2018-04-30T23:59:59Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1020_SESSIONEXACTLY12MONTHS1",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1021_SESSIONEXACTLY12MONTHS2",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1022_SESSIONEXACTLY13MONTHS3",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1023_SESSIONEXACTLY12MONTHS4",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1024_SESSIONEXACTLY12MONTHS5",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1025_SESSIONMORETHAN12MONTHS1",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1026_SESSIONMORETHAN12MONTHS2",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1027_SESSIONMORETHAN13MONTHS3",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1028_SESSIONMORETHAN12MONTHS4",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
            table5.AddRow(new string[] {
                        "COL1029_SESSIONMORETHAN12MONTHS5",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "NE9 7RG",
                        "true",
                        "",
                        "",
                        "90000001"});
#line 53
 testRunner.And("I load test session data for the feature", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "ParentRef",
                        "DateActionPlanCreated",
                        "CustomerCharterShownToCustomer",
                        "DateAndTimeCharterShown",
                        "DateActionPlanSentToCustomer",
                        "ActionPlanDeliveryMethod",
                        "DateActionPlanAcknowledged",
                        "PriorityCustomer",
                        "CurrentSituation"});
            table6.AddRow(new string[] {
                        "COL1015_SESSIONWITHIN12MONTHS1",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "true",
                        "2018-05-01T00:00:00Z",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1016_SESSIONWITHIN12MONTHS2",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "true",
                        "2018-05-01T00:00:00Z",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1017_SESSIONWITHIN13MONTHS3",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "true",
                        "2018-05-01T00:00:00Z",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1018_SESSIONWITHIN12MONTHS4",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "true",
                        "2018-05-01T23:59:59Z",
                        "2018-05-01T23:59:59Z",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1019_SESSIONWITHIN12MONTHS5",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "true",
                        "2018-05-01T23:59:59Z",
                        "2018-05-01T23:59:59Z",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1020_SESSIONEXACTLY12MONTHS1",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "true",
                        "2018-05-01T00:00:00Z",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1021_SESSIONEXACTLY12MONTHS2",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "true",
                        "2018-05-01T23:59:59Z",
                        "2018-05-01T23:59:59Z",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1022_SESSIONEXACTLY13MONTHS3",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "true",
                        "2018-05-01T00:00:00Z",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1023_SESSIONEXACTLY12MONTHS4",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "true",
                        "2018-05-01T00:00:00Z",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1024_SESSIONEXACTLY12MONTHS5",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "true",
                        "2018-05-01T23:59:59Z",
                        "2018-05-01T23:59:59Z",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1025_SESSIONMORETHAN12MONTHS1",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "true",
                        "2018-05-01T00:00:00Z",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1026_SESSIONMORETHAN12MONTHS2",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "true",
                        "2018-05-01T23:59:59Z",
                        "2018-05-01T23:59:59Z",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1027_SESSIONMORETHAN13MONTHS3",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "true",
                        "2018-05-01T00:00:00Z",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1028_SESSIONMORETHAN12MONTHS4",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "true",
                        "2018-05-01T00:00:00Z",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "2018-05-01T00:00:00Z",
                        "1",
                        "looking for work26"});
            table6.AddRow(new string[] {
                        "COL1029_SESSIONMORETHAN12MONTHS5",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "true",
                        "2018-05-01T23:59:59Z",
                        "2018-05-01T23:59:59Z",
                        "1",
                        "2018-05-01T23:59:59Z",
                        "1",
                        "looking for work26"});
#line 71
testRunner.And("I load action plan data for the feature", ((string)(null)), table6, "And ");
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "ParentRef",
                        "OutcomeType",
                        "TouchPoint",
                        "ClaimedPriorityGroup",
                        "OutcomeClaimedDate",
                        "OutcomeEffectiveDate"});
            table7.AddRow(new string[] {
                        "COL1015_SESSIONWITHIN12MONTHS1",
                        "1",
                        "1",
                        "",
                        "1",
                        "2019-04-29T23:59:00Z",
                        "2019-04-29T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1016_SESSIONWITHIN12MONTHS2",
                        "1",
                        "2",
                        "",
                        "2",
                        "2019-04-29T23:59:00Z",
                        "2019-04-29T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1017_SESSIONWITHIN13MONTHS3",
                        "1",
                        "3",
                        "",
                        "3",
                        "2019-05-29T23:59:00Z",
                        "2019-05-29T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1018_SESSIONWITHIN12MONTHS4",
                        "1",
                        "4",
                        "",
                        "4",
                        "2019-04-29T23:59:00Z",
                        "2019-04-29T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1019_SESSIONWITHIN12MONTHS5",
                        "1",
                        "5",
                        "",
                        "99",
                        "2019-04-29T23:59:00Z",
                        "2019-04-29T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1020_SESSIONEXACTLY12MONTHS1",
                        "1",
                        "1",
                        "",
                        "1",
                        "2019-04-30T23:59:00Z",
                        "2019-04-30T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1021_SESSIONEXACTLY12MONTHS2",
                        "1",
                        "2",
                        "",
                        "2",
                        "2019-04-30T23:59:00Z",
                        "2019-04-30T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1022_SESSIONEXACTLY13MONTHS3",
                        "1",
                        "3",
                        "",
                        "3",
                        "2019-05-30T23:59:00Z",
                        "2019-05-30T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1023_SESSIONEXACTLY12MONTHS4",
                        "1",
                        "4",
                        "",
                        "4",
                        "2019-04-30T23:59:00Z",
                        "2019-04-30T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1024_SESSIONEXACTLY12MONTHS5",
                        "1",
                        "5",
                        "",
                        "99",
                        "2019-04-30T23:59:00Z",
                        "2019-04-30T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1025_SESSIONMORETHAN12MONTHS1",
                        "1",
                        "1",
                        "",
                        "1",
                        "2019-04-30T23:59:00Z",
                        "2019-04-30T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1026_SESSIONMORETHAN12MONTHS2",
                        "1",
                        "2",
                        "",
                        "2",
                        "2019-04-30T23:59:00Z",
                        "2019-04-30T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1027_SESSIONMORETHAN13MONTHS3",
                        "1",
                        "3",
                        "",
                        "3",
                        "2019-05-30T23:59:00Z",
                        "2019-05-30T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1028_SESSIONMORETHAN12MONTHS4",
                        "1",
                        "4",
                        "",
                        "4",
                        "2019-04-30T23:59:00Z",
                        "2019-04-30T23:59:00Z"});
            table7.AddRow(new string[] {
                        "COL1029_SESSIONMORETHAN12MONTHS5",
                        "1",
                        "5",
                        "",
                        "99",
                        "2019-04-30T23:59:00Z",
                        "2019-04-30T23:59:00Z"});
#line 89
testRunner.And("I load outcome data for the feature", ((string)(null)), table7, "And ");
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "LoaderRef",
                        "SessionRef",
                        "DateandTimeOfSession"});
            table8.AddRow(new string[] {
                        "COL1020_SESSIONEXACTLY12MONTHS1",
                        "1",
                        "2018-04-30T00:00:00Z"});
            table8.AddRow(new string[] {
                        "COL1021_SESSIONEXACTLY12MONTHS2",
                        "1",
                        "2018-04-30T00:00:00Z"});
            table8.AddRow(new string[] {
                        "COL1022_SESSIONEXACTLY13MONTHS3",
                        "1",
                        "2018-04-30T00:00:00Z"});
            table8.AddRow(new string[] {
                        "COL1023_SESSIONEXACTLY12MONTHS4",
                        "1",
                        "2018-04-30T23:59:59Z"});
            table8.AddRow(new string[] {
                        "COL1024_SESSIONEXACTLY12MONTHS5",
                        "1",
                        "2018-04-30T23:59:59Z"});
            table8.AddRow(new string[] {
                        "COL1025_SESSIONMORETHAN12MONTHS1",
                        "1",
                        "2018-04-29T00:00:00Z"});
            table8.AddRow(new string[] {
                        "COL1026_SESSIONMORETHAN12MONTHS2",
                        "1",
                        "2018-04-29T00:00:00Z"});
            table8.AddRow(new string[] {
                        "COL1027_SESSIONMORETHAN13MONTHS3",
                        "1",
                        "2018-04-29T00:00:00Z"});
            table8.AddRow(new string[] {
                        "COL1028_SESSIONMORETHAN12MONTHS4",
                        "1",
                        "2018-04-29T23:59:59Z"});
            table8.AddRow(new string[] {
                        "COL1029_SESSIONMORETHAN12MONTHS5",
                        "1",
                        "2018-04-29T23:59:59Z"});
#line 107
testRunner.And("I update the following sessions", ((string)(null)), table8, "And ");
#line 122
testRunner.And("I have made any data fudging updates required", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
testRunner.And("I have confirmed all test data is now in the backup data store", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 124
testRunner.And("the report period start date is \"2019-04-01\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 125
testRunner.And("the report period end date is \"2020-03-31\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 126
testRunner.And("a request has been made and the report data is available", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 127
testRunner.And("I have completed loading data and don\'t want to repeat for each test", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Session closure checks")]
        [NUnit.Framework.CategoryAttribute("mytag")]
        public virtual void SessionClosureChecks()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Session closure checks", null, new string[] {
                        "mytag"});
#line 130
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 7
this.FeatureBackground();
#line 131
  testRunner.When("I check the report data", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 132
  testRunner.Then("Outcome 1 for test customer \"COL1015_SESSIONWITHIN12MONTHS1\" is included in the r" +
                    "eport", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 133
  testRunner.Then("Outcome 1 for test customer \"COL1016_SESSIONWITHIN12MONTHS2\" is included in the r" +
                    "eport", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 134
  testRunner.Then("Outcome 1 for test customer \"COL1017_SESSIONWITHIN13MONTHS3\" is included in the r" +
                    "eport", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 135
  testRunner.Then("Outcome 1 for test customer \"COL1018_SESSIONWITHIN12MONTHS4\" is included in the r" +
                    "eport", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 136
  testRunner.Then("Outcome 1 for test customer \"COL1019_SESSIONWITHIN12MONTHS5\" is included in the r" +
                    "eport", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 137
  testRunner.Then("Outcome 1 for test customer \"COL1020_SESSIONEXACTLY12MONTHS1\" is included in the " +
                    "report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 138
  testRunner.Then("Outcome 1 for test customer \"COL1021_SESSIONEXACTLY12MONTHS2\" is included in the " +
                    "report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 139
  testRunner.Then("Outcome 1 for test customer \"COL1022_SESSIONEXACTLY13MONTHS3\" is included in the " +
                    "report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 140
  testRunner.Then("Outcome 1 for test customer \"COL1023_SESSIONEXACTLY12MONTHS4\" is included in the " +
                    "report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 141
  testRunner.Then("Outcome 1 for test customer \"COL1024_SESSIONEXACTLY12MONTHS5\" is included in the " +
                    "report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 142
  testRunner.Then("Outcome 1 for test customer \"COL1025_SESSIONMORETHAN12MONTHS1\" is not included in" +
                    " the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 143
  testRunner.Then("Outcome 1 for test customer \"COL1026_SESSIONMORETHAN12MONTHS2\" is not included in" +
                    " the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 144
  testRunner.Then("Outcome 1 for test customer \"COL1027_SESSIONMORETHAN13MONTHS3\" is not included in" +
                    " the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 145
  testRunner.Then("Outcome 1 for test customer \"COL1028_SESSIONMORETHAN12MONTHS4\" is not included in" +
                    " the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 146
  testRunner.Then("Outcome 1 for test customer \"COL1029_SESSIONMORETHAN12MONTHS5\" is not included in" +
                    " the report", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion

